# SWE-Dev Configuration

paths:
  conda_bin: /raid/swedev/miniforge3/bin/conda
  conda_base: /raid/swedev/miniforge3/
  local_repo_dir: /raid/repos
  playground: /raid/playground

github:
  tokens: ghp_1,ghp_2 # split by comma
  api_url: https://api.github.com
  
# Pipeline stage-specific model settings
# These settings allow using different models for each stage
# If not specified, fallback to openai.base_model and openai.base_url
description:
  model: ${openai.base_model}
  base_url: ${openai.base_url}
  max_tokens: ${openai.max_tokens}

testcase:
  model: ${openai.base_model}
  base_url: ${openai.base_url}
  revise_rounds: 0  # Number of rounds to revise testcases
  max_tokens: ${openai.max_tokens}