# SWE-Dev Configuration

# Basic directory settings
paths:
  conda_bin: /raid/swedev/miniforge3/bin/conda
  conda_base: /raid/swedev/miniforge3/
  local_repo_dir: /raid/repos
  playground: /raid/playground

# API credentials
github:
  tokens: []  # Add your GitHub tokens here
  api_url: https://api.github.com

# OpenAI settings
openai:
  base_url: http://api.openai.com/v1
  base_model: gpt-4o
  api_key: ${oc.env:OPENAI_API_KEY,sk-test}

# Data collection settings
data_collection:
  max_repos: 5000
  max_pulls: 1000
  num_workers: 8

# Code localization settings
code_localization:
  top_n: 5
  num_workers: 128

# Test generation settings
test_generation:
  num_workers: 30
  model: ${openai.base_model}

# Test evaluation settings
test_evaluation:
  num_workers: 32
  docker:
    enabled: false
    image: testcase-image:latest

# Dataset creation settings
dataset_creation:
  output_folder: results/swedata
  dataset_type: openhands 