# @package _global_
defaults:
  - config/default
  - _self_

description:
  model: gpt-4o
  api_key: sk-swedev
  base_url: http://localhost:8000/v1
  max_tokens: 32768

testcase:
  model: gpt-4o
  api_key: sk-swedev
  base_url: http://localhost:8000/v1
  max_tokens: 32768